[toolchain]
anchor = "0.26.0"
solana = "1.16.0"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
pusd_escrow = "PUSDXqSqhN7s5EvWqRGrQB3JpGtK1Z3vN7aTqzK3XqYq"

[scripts]
test = "yarn run mocha -t 10000 tests/*.ts"